connectionProperties:
  mfhostAddress: "mainframe.openlegacy.com"
  mfport: "6800"
  as400hostAddress: ""
  connectionType: "Mainframe"
  defaultFilter: ""
generalSettings:
  hubUrl: http://ol-hub:8080
  hubApiKey: ${OL_HUB_API_KEY:}
  terminalUrl: "http://localhost:8081/emulation"
  mockServerEnabled: false
admin:
  username: "openlegacy"
  password: "olpassword"
aiSettings:
  aiModel: "gpt-5.1"
  aiApiKey: "${OL_AI_API_KEY:}"
  aiBaseUrl: ""