generalSettings:
  userNameLabel: user.*
  saveAllSessions: false
  hubUrl: http://ol-hub:8080
  hubApiKey: ${OL_HUB_API_KEY:}
  actionWebhook: http://ol-termiq:8080//api/runtime/snapshot/my-workspace
connectivityProperties:
  connectorType: client-terminal
  connectionType: TN3270
  sessionsPerIp: 2
  enableFlip: false
  devmode: true
  enablePrinterSupport: false
  printerQueueName: /QSYS.LIB/QUSRSYS.LIB/QPRINT.OUTQ
  sessionTimeout: 600
  enableMacros: true
  recordTraffic: false
  playerPort: 2023
  playerFile: ''
  keyboardUnlockTimeout: 3000
  beepOnScreenLock: false
  sessionSync: websocket
  enableTypeAhead: true
connectionProperties:
  trailFile: mainframe-cards.trail
  hostname: mainframe.openlegacy.com
  port: 623
  codePage: '037'
  sslType: NONE
  model: _24X80
logging:
  webhook:
    debugEnabled: false
    logPayload: false
    logHeaders: false
