generalSettings:
  hubUrl: http://ol-hub:8080
  hubApiKey:
database:
  timeouts:
    connection: 30
    query: 60
    validation: 10
  query:
    maxRows: 199
    pagination:
      defaultPageSize: 50
      maxPageSize: 1000
